### ISSUE TITLE
Apply For The Dataset

### ISSUE THREAD

**Issue by VictorZoo** [shiyujiao/CVLNet#1]
Hi Shiyujiao，

Recenlty, I confirmed my Research proposal which is Geo-Locolization. So, I think the KITTI-Satellite Maps Dataset is very important for my research. I have filled the Google Form provided by the Github website. If you could send me the dataset link, I will very appriciate it.

Thanks a lot

**Comment by YujiaoShi** [comment]
> 

Hello, thank you very much for your interest. 

I have tried my best to send everyone the dataset link who has filled out the Google Form. If I accidentally missed your inquiry, please fill out the form again. 

I appreciate your understanding!
