### ISSUE TITLE
Access to satellite images

### ISSUE THREAD

**Issue by nate-daba** [shiyujiao/CVLNet#4]
Hello Dr. Yujiao,

Thank you for your work in cross-view video geo-localization.

I wanted to get access to the satellite images. I have already filled out the Google form (twice) and submitted. I did provide my university research group email on the form. Therefore, I would like to kindly request access to the dataset link.

Thank you,
Natnael

**Comment by YujiaoShi** [comment]
Hi, Sorry for the late reply. I just sent you the link to the dataset. Plz let me know if it doesn't work. 

It is strange I did not get any notification from Google form. I will fix this bug. 

Thank you again for your interest to our work.
