### ISSUE TITLE
Request for the satellite images

### ISSUE THREAD

**Issue by Mabel0403** [shiyujiao/CVLNet#5]
Hello Dr. Yujiao,

Thank you for your work "CVLNet: Cross-view Semantic Correspondence Learning for Video-Based Camera Localization".

I'd like to get access to the satellite images in your KITTI-CVL Dataset. I have already filled out the Google form and submitted. I did provide my university research group email on the form. Therefore, I would like to kindly request access to the dataset link.

Thank you,
Mabel

**Comment by Larry2000error** [comment]
您好，请问您解决了这个问题，拿到数据了吗？

**Comment by Mabel0403** [comment]
你好，我拿到数据了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YujiaoShi/CVLNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2026年2月27日(星期五) 晚上9:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [YujiaoShi/CVLNet] Request for the satellite images (Issue #5)



Larry2000error left a comment (YujiaoShi/CVLNet#5)
 
您好，请问您解决了这个问题，拿到数据了吗？
